 /*
 ============================================================================
 Name        : Lab8.c
 Author      : Austin Tian
 Revised by  :
 Version     :
 Copyright   : Copyright 2020
 Description : Lab 8 in C, ANSI-C Style
 ============================================================================
 */

#include "header.h"

// Menu for the testing.
char *menu =    "\n" \
                " ***********Please select the following options**********************\n" \
                " *    This is the memory operation menu (Lab 8)                     *\n" \
                " ********************************************************************\n" \
                " *    1. Write a double-word (32-bit) to the memory                 *\n"  \
                " ********************************************************************\n" \
                " *    2. Read a byte (8-bit) data from the memory                   *\n" \
                " *    3. Read a double-word (32-bit) data from the memory           *\n" \
                " ********************************************************************\n" \
                " *    4. Generate a memory dump from any memory location            *\n" \
                " ********************************************************************\n" \
                " *    e. To Exit, Type 'e'  or 'E'                                  *\n" \
                " ********************************************************************\n";

//---------------------------------------------------------------
// Generate a random number between 0x00 and 0xFF.
unsigned char rand_generator()
{
    return rand()%255;  // generate a random number between 0 and 255.
}
//---------------------------------------------------------------
void free_memory(char *base_address)
{
    free(base_address);  // free memory after use to avoid memory leakage.
    return;
}
//---------------------------------------------------------------
char *init_memory()
{
    char *mem = malloc(MEM_SIZE);  // allocate the memory
    // step 0: Start filling in the memory contents with
    //         random number generated by rand_generator() etc.
    int i =0;
    for (i = 0; i<MEM_SIZE; i++){
        *(mem+i) = 0;
    }
    return mem;
}


//---------------------------------------------------------------
void write_byte(char *base_address, int offset, unsigned char byte_data){
    // Step 1: write a byte "data" to address: "base_address + offset".
    *(base_address + offset) = byte_data;
}

//---------------------------------------------------------------
void write_dword(char *base_address, int offset, unsigned int dword_data){
    // Step 2: write a double-word to address: "base_address + offset".
    unsigned int *data = (unsigned int*)(base_address + offset);
    *data = dword_data;
}
//---------------------------------------------------------------
unsigned char read_byte(char *base_address, int offset){
    unsigned char data;
    // Step 3: return and print the byte from address: "base_address + offset".
    data =  *(base_address + offset);
     if (DEBUG_CODE)
       printf("-----The Byte at base: %X, offset %X: %02X ------\n", (unsigned int) base_address, offset, data);
    return  data;
}
//---------------------------------------------------------------
unsigned int read_dword(char *base_address, int offset){
    // Step 4: return and print the double-word from address: "base_address + offset".
    unsigned int *dataptr = (unsigned int*)(base_address + offset);
    if (DEBUG_CODE)
       printf("-----The 32-bit word at base: %X, offset %X is: %08X ------\n", (unsigned int) base_address, offset, *dataptr);
    return  *dataptr;
}
//---------------------------------------------------------------
void memory_dump(char *base_address, int offset, unsigned int dumpsize){
    // Step 5: Generate a memory dump display starting from address "base_address + offset".
    //        i.e., Display the contents of dump_size bytes starting from  "base_address + offset"
    //        dump_size should be a parameter.
    //        The memory dump display should be like the screenshot on lab manual:
    unsigned char printout;
    int i=0, j=0;
    if (dumpsize < MIN_DUMP_SIZE || dumpsize > MEM_SIZE)
        dumpsize = MIN_DUMP_SIZE;  //
            printf("\n");

    for (i=0; i<dumpsize/DUMP_LINE; i++)
    {
        printf("%X: ", (unsigned int) base_address+offset+i*DUMP_LINE);
        for (j = 0; j< DUMP_LINE; j++)
        {
            printout = (unsigned char) (*(base_address+offset+i*DUMP_LINE+j) );
            printf("%02X ", printout);
        }
         printf(" --- ");
        for (j = 0; j< DUMP_LINE; j++)
        {
            printout = (unsigned char) (*(base_address+offset+i*DUMP_LINE+j) );
            if (printout > 0x20 && printout < 0x7E)
                printf("%c ", printout);
            else
                printf(". " );
        }
        printf("\n");
    }
    getchar();
    return;

}

/*
void clean_stdin(void)
{
    char c;
    do {
        c = getchar();
    } while (c != '\n' && c != EOF);
}*/

//---------------------------------------------------------------
void setup_memory()
{
    // Now we need to setup the memory controller for the computer system we
    // will build. Basic requirements:
    // 1. Memory size needs to be 1M Bytes
    // 2. Memory is readable/writable with Byte and Double-Word Operations.
    // 3. Memory can be dumped and shown on screen.
    // 4. Memory needs to be freed (released) at the end of the code.
    // 6. For lab 8, we need to have a user interface to fill in memory,
    //                                      read memory and do memory dump.
    char *mem = init_memory();  // initialize the memory.
    char options =0;
    unsigned int offset, dumpsize;
    char byte_data;    // 8-bit operation.
    unsigned int dword_data;      // 32-bit operation.
    do{
        if (options != 0x0a)  // if options has a return key input, skip it.
        {
            puts(menu); /* prints Memory Simulation */
            printf ("\nThe base address of your memory is: %Xh (HEX)\n", (unsigned int) mem);  // output base memory first.
            puts("Please make a selection:");  // output base memory first.
        }
            options = getchar();

            switch (options)
            {               
                case '1':  // write double word.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", (unsigned int*)&offset);    // input an offset address (in HEX) to write.
                    puts("Please input your DOUBLE WORD data to be written (in HEX):");
                    scanf("%x", (unsigned int*)&dword_data);    // input data
                    write_dword (mem, offset, dword_data);  // write a double word to memory.
                    continue;
                case '2':  // read byte.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to write.
                    read_byte(mem, offset);
                    continue;
                case '3':  // read double word.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to write.
                    read_dword(mem, offset);
                    continue;
                case '4':  // generate memory dump starting at offset address (in HEX).
                    puts("Please input your memory's offset address (in HEX, should be a multiple of 0x10h):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to start.
                    puts("Please input the size of the memory to be dumped (a number between 256 and 1024 ):");
                    scanf("%d", &dumpsize);    // The size of the memory dump
                    memory_dump(mem, offset, dumpsize);  // generate a memory dump display of dumpsize bytes.
                    continue;
                case 'e':
                case 'E':
                    puts("Code finished, exit now");
                    free_memory(mem);
                    getchar();
                    return;  // return to main program.
                default:
                    // puts("Not a valid entry, please try again");
                    continue;
            }
    }while (1);  // make sure the only exit is from 'e'.
    return;
}
